# Generated by Django 4.0.6 on 2022-07-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ant_personal', models.CharField(max_length=200)),
                ('ant_genetico', models.CharField(max_length=200)),
                ('predeterminado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('predeterminada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField(default=True)),
                ('est_civil', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=255)),
                ('num_telef', models.CharField(max_length=10)),
                ('tipo_sangre', models.CharField(max_length=4)),
                ('antecedentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.antecedentes')),
                ('personal_med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.personalmed')),
            ],
        ),
    ]
